WINDOW_WIDTH_RATIO = 0.75
WINDOW_HEIGHT_RATIO = 0.85

CANVAS_WIDTH_RATIO = 0.80
CANVAS_HEIGHT_RATIO = 0.90

BUTTON_WIDTH_RATIO = 0.01
BUTTON_HEIGHT_RATIO = 0.003

PADY_RATIO_1 = 0.02
PADY_RATIO_2 = 0.1

ALIVE_CELL_COLOR = "black"
DEAD_CELL_COLOR = "white"

canvas = None

cells = []