WINDOW_WIDTH_RATIO = 0.75
WINDOW_HEIGHT_RATIO = 0.85

CANVAS_WIDTH_RATIO = 0.80
CANVAS_HEIGHT_RATIO = 0.90

BUTTON_WIDTH_RATIO = 0.01
BUTTON_HEIGHT_RATIO = 0.003

CELL_SIZE = 30

ALIVE_CELL_COLOR = "black"
DEAD_CELL_COLOR = "white"

def adapt_canvas(num):
    return int(num - num % CELL_SIZE)